from typing import Literal

from pydantic import BaseModel, Field


# Output Structures
class ResearchReport(BaseModel):
    title: str = Field(..., description="The title of the research report.")
    content: str = Field(..., description="The main content of the research report.")
    references: list[str] = Field(..., description="A list of references used in the report.")

class AIOutputSchema(BaseModel):
    content: str = Field(..., description="Content generated by the AI.")
    additional_kwargs: dict = Field(default_factory=dict, description="Additional information related to the AI message.")

class ToolOutputSchema(BaseModel):
    content: str = Field(..., description="Content generated by the tool.")
    tool_name: str = Field(..., description="Name of the tool used.")
    tool_output: str = Field(..., description="Output produced by the tool.")

class OutputSchema(BaseModel):
    type: Literal["ai", "tool"] = Field(..., description="Type of the message chunk, either 'ai' or 'tool'.")
    chunk: AIOutputSchema | ToolOutputSchema = Field(..., description="The actual message chunk data.")